name: Monitorar AstroPay

on:
  schedule:
    - cron: "0 * * * *"

  workflow_dispatch:

jobs:
  monitorar:
    runs-on: ubuntu-latest

    steps:
      - name: Consultar AstroPay
        run: |
          resposta=$(curl -s -X POST \
            https://partners-api.astropay.com/v1/public/exchanges \
            -H "Content-Type: application/json" \
            -d '{"from":"BRL","to":"ARS"}')

          echo "Resposta da AstroPay:"
          echo "$resposta"
